Args = --initialize-at-build-time=io.netty \
       --initialize-at-run-time=io.netty.util.internal.logging.Log4JLogger \
       --initialize-at-run-time=io.netty.util.internal.PlatformDependent0 \
       --initialize-at-run-time=io.netty.util.internal.PlatformDependent \
       --initialize-at-run-time=io.netty.buffer.PooledByteBufAllocator \
       --initialize-at-run-time=io.netty.buffer.ByteBufAllocator \
       --initialize-at-run-time=io.netty.buffer.AbstractByteBufAllocator \
       --initialize-at-run-time=io.netty.channel.epoll.Native \
       --initialize-at-run-time=io.netty.channel.epoll.Epoll \
       --initialize-at-run-time=io.netty.channel.epoll.EpollEventLoop \
       --initialize-at-run-time=io.netty.channel.kqueue.Native \
       --initialize-at-run-time=io.netty.channel.kqueue.KQueue \
       --initialize-at-run-time=io.netty.channel.kqueue.KQueueEventLoop \
       --initialize-at-run-time=io.netty.channel.unix.Errors \
       --initialize-at-run-time=io.netty.channel.unix.FileDescriptor \
       --initialize-at-run-time=io.netty.channel.unix.Socket
